"""
ChromaDB Memory Manager — two-collection persistent + session memory.

Design (Yukta's original contribution):
- phantom_session_memory  : cleared each session
- phantom_persistent_memory: survives restarts; only HITL-approved entries

Write-back is outcome-gated:
- Always write to session_memory.
- Write to persistent_memory ONLY IF hitl_approved=True AND not degraded.

Summaries are generated by the local LLM before storage. A PII check is run
on the summary before it is stored in ChromaDB.
"""

from __future__ import annotations

import datetime
import os
import shutil
import time
import uuid
from typing import Optional

from utils.config import (
    CHROMA_PERSIST_DIR,
    OLLAMA_MODEL,
    PERSISTENT_COLLECTION,
    PROJECT_ROOT as _PROJECT_ROOT,
    SESSION_COLLECTION,
    get_best_available_model,
)
from utils.exceptions import ChromaDBCorruptionError, MemoryWriteError


class ChromaManager:
    """Manages session and persistent ChromaDB collections for PHANTOM memory."""

    def __init__(
        self,
        persist_dir: str = CHROMA_PERSIST_DIR,
        session_only: bool = False,
    ):
        """
        Args:
            persist_dir  : Path for PersistentClient (ignored when session_only=True).
            session_only : If True, use chromadb.Client() — in-memory, ephemeral,
                           session-scoped. No data survives process exit.
                           Set via PHANTOM_SESSION_ONLY=true env var or this flag.
                           Default False keeps the existing file-backed behaviour.
        """
        self._session_only = session_only
        self._persist_dir = os.path.abspath(persist_dir)
        if not session_only:
            os.makedirs(self._persist_dir, exist_ok=True)
        self._client = None
        self._session_col = None
        self._persistent_col = None
        self._embedder = None
        self._init_client()

    # ── Initialisation ────────────────────────────────────────────────────────

    def _init_client(self) -> None:
        try:
            import chromadb
            from chromadb.config import Settings

            if self._session_only:
                # In-memory ephemeral client — session-scoped, no disk writes
                self._client = chromadb.Client()
            else:
                settings = Settings(
                    anonymized_telemetry=False,
                    allow_reset=True,
                )
                try:
                    self._client = chromadb.PersistentClient(
                        path=self._persist_dir,
                        settings=settings,
                    )
                except Exception as e:
                    if "different settings" in str(e) or "already exists" in str(e):
                        # Dev-mode auto-recovery: wipe and reinitialise cleanly
                        import shutil
                        import logging
                        logging.getLogger(__name__).warning(
                            "[ChromaDB] Settings conflict detected — wiping and reinitialising: %s", e
                        )
                        shutil.rmtree(self._persist_dir, ignore_errors=True)
                        os.makedirs(self._persist_dir, exist_ok=True)
                        self._client = chromadb.PersistentClient(
                            path=self._persist_dir,
                            settings=settings,
                        )
                    else:
                        raise

            self._session_col = self._client.get_or_create_collection(
                name=SESSION_COLLECTION,
                metadata={
                    "description": "PHANTOM session memory — cleared each session",
                    "hnsw:space": "cosine",
                },
            )
            self._persistent_col = self._client.get_or_create_collection(
                name=PERSISTENT_COLLECTION,
                metadata={
                    "description": "PHANTOM persistent memory — HITL-approved only",
                    "hnsw:space": "cosine",
                },
            )
        except Exception as e:
            raise ChromaDBCorruptionError(f"ChromaDB init failed: {e}") from e


    def _get_embedder(self):
        """Lazy-load sentence-transformers embedder. Falls back to None if unavailable."""
        if self._embedder is not None:
            return self._embedder
        try:
            from sentence_transformers import SentenceTransformer
            self._embedder = SentenceTransformer("all-MiniLM-L6-v2")
            return self._embedder
        except ImportError:
            return None

    def _embed(self, text: str) -> Optional[list[float]]:
        """Embed text using sentence-transformers. Returns None if unavailable."""
        embedder = self._get_embedder()
        if embedder is None:
            return None
        return embedder.encode(text, convert_to_numpy=True).tolist()

    # ── Write-back ────────────────────────────────────────────────────────────

    def write_back(
        self,
        interaction_summary: str,
        intent_type: str,
        outcome: str,
        hitl_approved: bool,
        cloud_used: bool = False,
        fallback: bool = False,
    ) -> None:
        """
        Store an interaction in ChromaDB.

        SAFETY: never store restored PII in vector DB. `interaction_summary`
        must be built from the pre-restoration LLM response (still holding
        [PII_*] placeholders), never the post-restoration text with real
        values substituted back in. This method's own summarizer
        (_make_privacy_safe_summary) is a second privacy layer, but it
        degrades to a 3-pattern regex fallback when Ollama is unreachable and
        would miss PII types it doesn't cover — so the caller (currently
        phantom_graph.py's pii_restore_node -> _write_to_memory) is the one
        actually responsible for this guarantee; it must never pass restored
        text here regardless of how good this method's own scrubbing is.

        Outcome-gated promotion (Yukta's original design):
        - Always writes to session_memory.
        - Writes to persistent_memory ONLY IF hitl_approved=True AND not fallback.
        """
        summary = self._make_privacy_safe_summary(interaction_summary)
        if not self._is_pii_safe(summary):
            # Don't store PII in the database under any circumstances
            summary = "[Interaction logged — summary withheld due to PII detection]"

        doc_id = str(uuid.uuid4())
        now_iso = datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z")
        embedding = self._embed(summary)

        metadata = {
            "timestamp": now_iso,
            "intent_type": intent_type,
            "outcome": outcome,
            "user_approved": hitl_approved,
            "retrieval_count": 0,
            "days_since_stored": 0.0,
            "cloud_used": cloud_used,
            "fallback": fallback,
        }

        try:
            add_kwargs: dict = dict(
                ids=[doc_id],
                documents=[summary],
                metadatas=[metadata],
            )
            if embedding is not None:
                add_kwargs["embeddings"] = [embedding]

            self._session_col.add(**add_kwargs)

            if hitl_approved and not fallback:
                self._persistent_col.add(**add_kwargs)

        except Exception as e:
            raise MemoryWriteError(f"ChromaDB write-back failed: {e}") from e

    # ── Search / Retrieval ────────────────────────────────────────────────────

    def distance_space(self, collection: str = "persistent") -> str:
        """
        The distance metric this collection actually uses ("cosine" | "l2" | "ip").

        Read off the live collection rather than assumed: get_or_create_collection
        only applies the requested hnsw:space when it CREATES the collection, so a
        collection first created before that metadata was passed keeps ChromaDB's
        default (l2) forever. Callers converting distance->similarity need the real
        metric; assuming cosine against an l2 collection silently inverts scores.
        """
        col = self._persistent_col if collection == "persistent" else self._session_col
        try:
            cfg = getattr(col, "configuration_json", None) or {}
            space = (cfg.get("hnsw") or {}).get("space")
            if space:
                return str(space)
        except Exception:
            pass
        try:
            return str((col.metadata or {}).get("hnsw:space", "l2"))
        except Exception:
            return "l2"

    def search(
        self, query: str, n_results: int = 5, collection: str = "persistent"
    ) -> list[dict]:
        """
        Search the specified collection for semantically similar documents.

        Returns list of dicts with keys: id, document, metadata, distance, space.
        Uses embedding search if sentence-transformers is available,
        falls back to keyword-based (ChromaDB default) otherwise.
        """
        col = self._persistent_col if collection == "persistent" else self._session_col
        embedding = self._embed(query)
        space = self.distance_space(collection)

        try:
            if embedding is not None:
                results = col.query(
                    query_embeddings=[embedding],
                    n_results=min(n_results, col.count() or 1),
                    include=["documents", "metadatas", "distances"],
                )
            else:
                results = col.query(
                    query_texts=[query],
                    n_results=min(n_results, col.count() or 1),
                    include=["documents", "metadatas", "distances"],
                )

            docs = results.get("documents", [[]])[0]
            metas = results.get("metadatas", [[]])[0]
            dists = results.get("distances", [[]])[0]
            ids = results.get("ids", [[]])[0]

            entries = []
            for doc_id, doc, meta, dist in zip(ids, docs, metas, dists):
                entries.append(
                    {
                        "id": doc_id,
                        "document": doc,
                        "metadata": meta,
                        "distance": dist,
                        "space": space,
                    }
                )
            return entries

        except Exception:
            return []

    def clear_session_memory(self) -> None:
        """Clear the session collection. Call at the start of each new session."""
        try:
            self._client.delete_collection(SESSION_COLLECTION)
            self._session_col = self._client.get_or_create_collection(
                name=SESSION_COLLECTION,
                metadata={"description": "PHANTOM session memory — cleared each session"},
            )
        except Exception:
            pass

    def count(self, collection: str = "persistent") -> int:
        col = self._persistent_col if collection == "persistent" else self._session_col
        return col.count()

    # ── Backup ────────────────────────────────────────────────────────────────

    def backup(self, backup_dir: str = os.path.join(_PROJECT_ROOT, "data", "backups")) -> str:
        """
        Create a timestamped backup of the ChromaDB directory.
        Keeps only the last 5 backups.
        Returns the path of the created backup.
        """
        os.makedirs(backup_dir, exist_ok=True)
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        dest = os.path.join(backup_dir, f"chromadb_backup_{timestamp}")
        shutil.copytree(self._persist_dir, dest, dirs_exist_ok=True)

        # Keep only last 5 backups
        backups = sorted(
            [d for d in os.listdir(backup_dir) if d.startswith("chromadb_backup_")]
        )
        for old in backups[:-5]:
            shutil.rmtree(os.path.join(backup_dir, old), ignore_errors=True)

        return dest

    # ── Privacy Helpers ───────────────────────────────────────────────────────

    def _make_privacy_safe_summary(self, text: str) -> str:
        """
        Ask the local LLM to generate a privacy-safe 2–3 sentence summary.
        Falls back to truncated original if LLM is unavailable.
        """
        try:
            import ollama

            prompt = (
                "Summarise this interaction in 2-3 sentences without including any "
                "personal details, names, or identifiers. Focus on what task was "
                "performed and what the outcome was.\n\n"
                f"Interaction:\n{text[:500]}"
            )
            model = get_best_available_model()
            response = ollama.generate(
                model=model,
                prompt=prompt,
                options={"temperature": 0.1, "num_predict": 128},
            )
            return response["response"].strip()
        except Exception:
            # Non-LLM fallback — truncate and strip obvious PII patterns
            import re
            clean = re.sub(
                r"\b[A-Z]{5}[0-9]{4}[A-Z]\b"  # PAN
                r"|\b[2-9]\d{3}\s\d{4}\s\d{4}\b"  # Aadhaar
                r"|\b[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+\b",  # email
                "[REDACTED]",
                text,
            )
            return clean[:300]

    def _is_pii_safe(self, text: str) -> bool:
        """Quick check: does the text contain any PHANTOM PII placeholders or raw PII?"""
        import re

        # If placeholders are present, PII was not fully resolved
        if re.search(r"\[PII_[A-Z]+_\d+\]", text):
            return False
        return True
